nc_votes/urls.py
#!/usr/bin/env python3
"""nc_votes URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('voters.urls')),
    path('', include('social_django.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

voters/urls.py
#!/usr/bin/env python3
"""voters app URL Configuration
"""
from django.contrib import admin
from django.urls import include, path, re_path
from .views import VoterSampleView, VoterDetailView, voter_count

app_name = 'voters'
urlpatterns = [
    path('', VoterSampleView.as_view(), name='sample'),
    re_path('(?P<ncid>[A-Z]{2}\d+)/', VoterDetailView.as_view(), name='detail'),
    path('count/', voter_count)
]

voter/models.py
from django.db import models

# Create your models here.
class NCVHis(models.Model):

    class Meta:
        verbose_name = "NC Voter History"
        verbose_name_plural = "NC Voter Histories"

    @staticmethod
    def parse_row(row):
        county_id = int(row['county_id'])
        row['county_id'] = county_id
        voted_county_id = int(row['voted_county_id'])
        row['voted_county_id'] = voted_county_id
        election_lbl_str = row['election_lbl']
        election_lbl_dt = datetime.strptime(election_lbl_str, '%m/%d/%Y')
        row['election_lbl'] = election_lbl_dt.date()
        return row

    @staticmethod
    def parse_existing(row):
        election_lbl_str = row.get('election_lbl')
        if election_lbl_str:
            election_lbl_dt = datetime.strptime(election_lbl_str, '%Y-%m-%d')
            row['election_lbl'] = election_lbl_dt.date()
        return row

    ncid = models.CharField('ncid', max_length=12, db_index=True)
    voter = models.ForeignKey('NCVoter', on_delete=models.CASCADE, related_name="histories", to_field='ncid', null=True)
    county_id = models.SmallIntegerField('county_id', db_index=True)
    county_desc = models.CharField('county_desc', max_length=60, blank=True)
    voter_reg_num = models.CharField('voter_reg_num', max_length=12, blank=True)
    election_lbl = models.DateField( max_length=10, blank=True)
    election_desc = models.CharField('election_desc', max_length=230, blank=True, db_index=True)
    voting_method = models.CharField('voting_method', max_length=32, blank=True)
    voted_party_cd = models.CharField('voted_party_cd', max_length=3, blank=True)
    voted_party_desc = models.CharField('voted_party_desc', max_length=60, blank=True)
    pct_label = models.CharField('pct_label', max_length=6, blank=True)
    pct_description = models.CharField('pct_description', max_length=60, blank=True)
    voted_county_id = models.SmallIntegerField('voted_county_id')
    voted_county_desc = models.CharField('voted_county_desc', max_length=60, blank=True)
    vtd_label = models.CharField('vtd_label', max_length=6, blank=True)
    vtd_description = models.CharField('vtd_description', max_length=60, blank=True)


class NCVoter(models.Model):

    class Meta:
        verbose_name = "NC Voter"
        verbose_name_plural = "NC Voters"

    @staticmethod
    def parse_row(row):
        county_id = int(row['county_id'])
        row['county_id'] = county_id
        birth_age = int(row['birth_age'])
        row['birth_age'] = birth_age
        drivers_lic_str = row.get('drivers_lic', '')
        drivers_lic = (drivers_lic_str == 'Y' or drivers_lic_str == 'y')
        row['drivers_lic'] = drivers_lic
        registr_dt_str = row['registr_dt']
        registr_dt = datetime.strptime(registr_dt_str, '%m/%d/%Y')
        row['registr_dt'] = registr_dt.date()
        confidential_ind_str = row.get('confidential_ind', '')
        row['confidential_ind'] = (confidential_ind_str == "Y")
        raw_birth_year = row.get('birth_year')
        if raw_birth_year:
            row['birth_year'] = int(raw_birth_year)
        return row

    @staticmethod
    def parse_existing(row):
        registr_dt_str = row.get('registr_dt')
        if registr_dt_str:
            registr_dt = datetime.strptime(registr_dt_str, '%Y-%m-%d')
            row['registr_dt'] = registr_dt.date()
        return row

    ncid = models.CharField('ncid', max_length=12, unique=True, db_index=True)
    county_id = models.SmallIntegerField(db_index=True)
    birth_age = models.IntegerField()
    birth_year = models.IntegerField(null=True)
    confidential_ind = models.BooleanField()
    birth_state = models.CharField('birth state', max_length=2)
    age = models.TextField()
    county_desc = models.CharField('county_desc', max_length=15)
    voter_reg_num = models.CharField('voter_reg_num', max_length=12)
    status_cd = models.CharField('status_cd', max_length=2)
    voter_status_desc = models.CharField('voter_status_desc', max_length=25)
    reason_cd = models.CharField('reason_cd', max_length=2)
    voter_status_reason_desc = models.CharField('voter_status_reason_desc', max_length=60)
    # FIXME: Migrate to BooleanField
    absent_ind = models.CharField('absent_ind', max_length=1)
    name_prefx_cd = models.CharField('name_prefx_cd', max_length=4)
    last_name = models.CharField('last_name', max_length=25)
    middle_name = models.CharField('middle_name', max_length=25)
    first_name = models.CharField('first_name', max_length=20)
    name_suffix_lbl = models.CharField('name_suffix_lbl', max_length=30)
    midl_name = models.CharField('midl_name', max_length=20)
    name_sufx_cd = models.CharField('name_sufx_cd', max_length=3)
    res_street_address = models.CharField('res_street_address', max_length=63)
    res_city_desc = models.CharField('res_city_desc', max_length=60)
    state_cd = models.CharField('state_cd', max_length=2)
    zip_code = models.CharField('zip_code', max_length=9)
    mail_addr1 = models.CharField('mail_addr1', max_length=40)
    mail_addr2 = models.CharField('mail_addr2', max_length=40)
    mail_addr3 = models.CharField('mail_addr3', max_length=40)
    mail_addr4 = models.CharField('mail_addr4', max_length=40)
    mail_city = models.CharField('mail_city', max_length=30)
    mail_state = models.CharField('mail_state', max_length=2)
    mail_zipcode = models.CharField('mail_zipcode', max_length=9)
    full_phone_number = models.CharField('full_phone_number', max_length=12)
    race_code = models.CharField('race_code', max_length=3)
    ethnic_code = models.CharField('ethnic_code', max_length=3)
    party_cd = models.CharField('party_cd', max_length=3)
    gender_code = models.CharField('gender_code', max_length=1)
    birth_place = models.CharField('birth_place', max_length=30)
    drivers_lic = models.BooleanField('drivers_lic')
    registr_dt = models.DateField('registr_dt')
    precinct_abbrv = models.CharField('precinct_abbrv', max_length=6)
    precinct_desc = models.CharField('precinct_desc', max_length=60)
    municipality_abbrv = models.CharField('municipality_abbrv', max_length=6)
    municipality_desc = models.CharField('municipality_desc', max_length=60)
    ward_abbrv = models.CharField('ward_abbrv', max_length=6)
    ward_desc = models.CharField('ward_desc', max_length=60)
    cong_dist_abbrv = models.CharField('cong_dist_abbrv', max_length=6)
    super_court_abbrv = models.CharField('super_court_abbrv', max_length=6)
    judic_dist_abbrv = models.CharField('judic_dist_abbrv', max_length=6)
    nc_senate_abbrv = models.CharField('nc_senate_abbrv', max_length=6)
    nc_house_abbrv = models.CharField('nc_house_abbrv', max_length=6)
    county_commiss_abbrv = models.CharField('county_commiss_abbrv', max_length=6)
    county_commiss_desc = models.CharField('county_commiss_desc', max_length=60)
    township_abbrv = models.CharField('township_abbrv', max_length=6)
    township_desc = models.CharField('township_desc', max_length=60)
    school_dist_abbrv = models.CharField('school_dist_abbrv', max_length=6)
    school_dist_desc = models.CharField('school_dist_desc', max_length=60)
    fire_dist_abbrv = models.CharField('fire_dist_abbrv', max_length=6)
    fire_dist_desc = models.CharField('fire_dist_desc', max_length=60)
    water_dist_abbrv = models.CharField('water_dist_abbrv', max_length=6)
    water_dist_desc = models.CharField('water_dist_desc', max_length=60)
    sewer_dist_abbrv = models.CharField('sewer_dist_abbrv', max_length=6)
    sewer_dist_desc = models.CharField('sewer_dist_desc', max_length=60)
    sanit_dist_abbrv = models.CharField('sanit_dist_abbrv', max_length=6)
    sanit_dist_desc = models.CharField('sanit_dist_desc', max_length=60)
    rescue_dist_abbrv = models.CharField('rescue_dist_abbrv', max_length=6)
    rescue_dist_desc = models.CharField('rescue_dist_desc', max_length=60)
    munic_dist_abbrv = models.CharField('munic_dist_abbrv', max_length=6)
    munic_dist_desc = models.CharField('munic_dist_desc', max_length=60)
    dist_1_abbrv = models.CharField('dist_1_abbrv', max_length=6)
    dist_1_desc = models.CharField('dist_1_desc', max_length=60)
    dist_2_abbrv = models.CharField('dist_2_abbrv', max_length=6)
    dist_2_desc = models.CharField('dist_2_desc', max_length=60)
    vtd_abbrv = models.CharField('vtd_abbrv', max_length=6)
    vtd_desc = models.CharField('vtd_desc', max_length=60)

voters/models/base.py
#!/usr/bin/env python3
"""
Base classes for customizing Django's Model and ModelField subclasses.
"""
from django.db import models


class VoterFieldMixin(models.Field):
    """
    """
    def __init__(self, *args, voter_column_name=None, **kwargs):
        """
        Overrides the standard __init__ to add voter_column_name kwarg.
        """
        self.voter_column_name = voter_column_name
        super().__init__(*args, **kwargs)

    def deconstruct(self):
        """
        Overrides the standard deconstruct method to add voter_column_name args.
        """
        name, path, args, kwargs = super().deconstruct()
        if self.voter_column_name:
            kwargs['voter_column_name'] = self.voter_column_name
        return name, path, args, kwargs


class VoterBooleanField(models.BooleanField, VoterFieldMixin):
    """
    """


class VoterCharField(models.CharField, VoterFieldMixin):
    """
    """


class VoterDateField(models.DateField, VoterFieldMixin):
    """
    """


class VoterForeignKey(models.ForeignKey, VoterFieldMixin):
    """
    """


class VoterIntegerField(models.IntegerField, VoterFieldMixin):
    """
    """


class VoterSmallIntegerField(models.SmallIntegerField, VoterFieldMixin):
    """
    """

voters/models/voter_history.py
#!/usr/bin/env python3
"""
Models related to voting history of North Carolina voters.
"""
from django.db import models
from django.contrib.postgres.functions import RandomUUID
from .voter import Voter


class Election(models.Model):
    """
    An election in which a voter may have voted.
    """
    id = models.UUIDField(
        primary_key=True,
        default=RandomUUID(),
        editable=False,
        help_text='Randomly generated universal unique identifier.',
    )
    date = models.DateField()
    name = models.CharField(max_length=100)

    class Meta:
        unique_together = (("date", "name"),)
        ordering = ['-date', 'name']

    def __str__(self):
        return f'{self.name} ({self.date})'


class ElectionNameTranslator(models.Model):
    """
    """
    date = models.DateField()
    clean_name = models.CharField(max_length=100)
    raw_name = models.CharField(max_length=100)


class VoterHistory(models.Model):
    """
    The registration and voting status of a given voter in each election.
    """
    voter = models.ForeignKey(
        'Voter',
        on_delete=models.SET_NULL,
        related_name="histories",
        null=True,
    )
    voter_reg_num = models.CharField(max_length=12, blank=True)
    election = models.ForeignKey(
        'Election',
        on_delete=models.CASCADE,
        help_text='Refers to the election in which the vote was cast.'
    )
    voting_method = models.CharField(max_length=32, blank=True)
    voted_party_cd = models.CharField(max_length=3, blank=True)
    county_id = models.SmallIntegerField(db_index=True)
    voted_county_id = models.SmallIntegerField()

voter/views.py
from django.shortcuts import render

# Create your views here.

voters/views.py
#!/usr/bin/env python3
"""
Views for North Carolina voters 
"""
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .filters import VoterFilter
from .models import Voter


class VoterSampleView(LoginRequiredMixin, generic.ListView):
    """
    A sample of voters.
    """

    template_name = 'voters/sample.html'

    def get_queryset(self):
        """
        Return ten random voters.
        """
        return Voter.objects.order_by('?')[:10]


class VoterDetailView(LoginRequiredMixin, generic.DetailView):
    """
    A voter's full details.
    """

    model = Voter
    template_name = 'voters/detail.html'
    pk_url_kwarg = 'ncid'


@login_required
def voter_count(request):
    f = VoterFilter(request.GET)
    return render(
        request, 'voters/filter.html', {'filter': f, 'count': f.qs.count()}
    )

templates/voters/base.html
<html>
<head>
    <link href="https://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
    body {
      padding-top: 2rem;
      padding-bottom: 2rem;
    }
    h3, h4, h5 {
        padding: 2rem 0 0.5rem 0;
    }
    .table ul {
        padding-left: 0;
        margin-bottom: 0;
        list-style-type: none;
    }
    </style>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>
<body>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

templates/voters/detail.html
{% extends "voters/base.html" %}

{% block content %}

    <h1>{{ object.name }}</h1>

    <table class="table table-sm">
        <tr>
            <th>NCID</th>
            <td>{{ object.ncid }}</td>
        </tr>
        <tr>
            <th>First name</th>
            <td>{{ object.first_name }}</td>
        </tr>
        <tr>
            <th>Middle name</th>
            <td>{{ object.middle_name }}</td>
        </tr>
        <tr>
            <th>Last name</th>
            <td>{{ object.last_name }}</td>
        </tr>
        <tr>
            <th>Suffix</th>
            <td>{{ object.name_suffix_lbl }}</td>
        </tr>
        <tr>
            <th>Age</th>
            <td>{{ object.birth_age }}</td>
        </tr>
        <tr>
            <th>Race</th>
            <td>{{ object.get_race_code_display }}</td>
        </tr>
        <tr>
            <th>Ethnicity</th>
            <td>{{ object.get_ethnic_code_display }}</td>
        </tr>
        <tr>
            <th>Gender</th>
            <td>{{ object.get_gender_code_display }}</td>
        </tr>
        <tr>
            <th>Confidentiality</th>
            <td>{{ object.confidential_ind }}</td>
        </tr>
        <tr>
            <th>Voter Registration Number</th>
            <td>{{ object.voter_reg_num }}</td>
        </tr>
        <tr>
            <th>Registration Date</th>
            <td>{{ object.registr_dt }}</td>
        </tr>
        <tr>
            <th>Voter Status</th>
            <td>{{ object.voter_status_desc }} ({{ object.voter_status_reason_desc }})</td>
        </tr>
        <tr>
            <th>Party</th>
            <td>{{ object.get_party_cd_display }}</td>
        </tr>
        <tr>
            <th>Residential Address</th>
            <td>
                <p>{{ object.res_street_address }}</p>
                <p>{{ object.res_city_desc }}, {{ object.state_cd }} {{ object.zip_code }}</p>
            </td>
        </tr>
        <tr>
            <th>Mailing Address </th>
            <td>
                <p>{{ object.mail_addr1 }}</p>
                <p>{{ object.mail_addr2 }}</p>
                <p>{{ object.mail_addr3 }}</p>
                <p>{{ object.mail_addr4 }}</p>
                <p>{{ object.mail_city }}, {{ object.mail_state }} {{ object.mail_zipcode }}</p>
            </td>
        </tr>
        <tr>
            <th>full_phone_number</th>
            <td>{{ object.full_phone_number }}</td>
        </tr>
        <tr>
            <th>county_desc</th>
            <td>{{ county_desc }}</td>
        <tr>
            <th>precinct_desc</th>
            <td>{{ object.precinct_desc }} ({{ object.precinct_abbrv }})</td>
        <tr>
            <th>municipality_desc</th>
            <td>{{ object.municipality_desc }} ({{ object.municipality_abbrv }})</td>
        <tr>
            <th>ward_desc</th>
            <td>{{ object.ward_desc }} ({{ object.ward_abbrv }})</td>
        <tr>
            <th>cong_dist_abbrv</th>
            <td>{{ object.cong_dist_abbrv }}</td>
        <tr>
            <th>super_court_abbrv</th>
            <td>{{ object.super_court_abbrv }}</td>
        <tr>
            <th>judic_dist_abbrv</th>
            <td>{{ object.judic_dist_abbrv }}</td>
        <tr>
            <th>nc_senate_abbrv</th>
            <td>{{ object.nc_senate_abbrv }}</td>
        <tr>
            <th>nc_house_abbrv</th>
            <td>{{ object.nc_house_abbrv }}</td>
        <tr>
            <th>county_commiss_desc</th>
            <td>{{ object.county_commiss_desc }} ({{ object.county_commiss_abbrv }})</td>
        <tr>
            <th>township_desc</th>
            <td>{{ object.township_desc }} ({{ object.township_abbrv }})</td>
        <tr>
            <th>school_dist_desc</th>
            <td>{{ object.school_dist_desc }} ({{ object.school_dist_abbrv }})</td>
        <tr>
            <th>fire_dist_desc</th>
            <td>{{ object.fire_dist_desc }} ({{ object.fire_dist_abbrv }})</td>
        <tr>
            <th>water_dist_desc</th>
            <td>{{ object.water_dist_desc }} ({{ object.water_dist_abbrv }})</td>
        <tr>
            <th>sewer_dist_desc</th>
            <td>{{ object.sewer_dist_desc }} ({{ object.sewer_dist_abbrv }})</td>
        <tr>
            <th>sanit_dist_desc</th>
            <td>{{ object.sanit_dist_desc }} ({{ object.sanit_dist_abbrv }})</td>
        <tr>
            <th>rescue_dist_desc</th>
            <td>{{ object.rescue_dist_desc }} ({{ object.rescue_dist_abbrv }})</td>
        <tr>
            <th>munic_dist_desc</th>
            <td>{{ object.munic_dist_desc }} ({{ object.munic_dist_abbrv }})</td>
        <tr>
            <th>dist_1_desc</th>
            <td>{{ object.dist_1_desc }} ({{ object.dist_1_abbrv }})</td>
        <tr>
            <th>dist_2_desc</th>
            <td>{{ object.dist_2_desc }} ({{ object.dist_2_abbrv }})</td>
        <tr>
            <th>vtd_desc</th>
            <td>{{ object.vtd_desc }}</td>

</table>

{% endblock %}

templates/voters/filter.html
{% extends "voters/base.html" %}
{% load humanize %}

{% block content %}
    <h1>Voters: {{ count|intcomma }}</h1>
    <hr>
    <form action="" method="get">
        <div class="ageWrapper">
            {{ filter.form.birth_age_gt.label_tag }}
            {{ filter.form.birth_age_gt }}
            {{ filter.form.birth_age_lt.label_tag }}
            {{ filter.form.birth_age_lt }}
        </div>
        <div>
            {{ filter.form.birth_state.label_tag }}
            {{ filter.form.birth_state }}            
        </div>
        <div class="genderWrapper">
            {{ filter.form.gender_code.label_tag }}
            {{ filter.form.gender_code }}
        </div>
        <div class="raceWrapper">
            {{ filter.form.race_code.label_tag }}
            {{ filter.form.race_code }}
        </div>
        <div class="ethnicityWrapper">
            {{ filter.form.ethnic_code.label_tag }}
            {{ filter.form.ethnic_code }}
        </div>
        <div class="regDateWrapper">
            {{ filter.form.registr_dt__gt.label_tag }}
            {{ filter.form.registr_dt__gt }}
            {{ filter.form.registr_dt__lt.label_tag }}
            {{ filter.form.registr_dt__lt }}
        </div>
        <div class="partyWrapper">
            {{ filter.form.party_cd.label_tag }}
            {{ filter.form.party_cd }}
        </div>
        <div class="countyWrapper">
            {{ filter.form.county.label_tag }}
            {{ filter.form.county }}
        </div>

        <div class="congressionalDistrictWrapper">
            {{ filter.form.congressional.label_tag }}
            {{ filter.form.congressional }}
        </div>
        <div class="stateSenateDistrictWrapper">
            {{ filter.form.state_senate.label_tag }}
            {{ filter.form.state_senate }}
        </div>
        <div class="stateHouseDistrictWrapper">
            {{ filter.form.state_house.label_tag }}
            {{ filter.form.state_house }}
        </div>
        <div class="superiorCourtDistrictWrapper">
            {{ filter.form.superior_court.label_tag }}
            {{ filter.form.superior_court }}
        </div>
        <div class="votedInWrapper">
            {{ filter.form.histories_election_include.label_tag }}
            {{ filter.form.histories_election_include }}
        </div>
        <div class="didNotVoteInWrapper">
            {{ filter.form.histories_election_exclude.label_tag }}
            {{ filter.form.histories_election_exclude }}
        </div>
        <div>
            <input type="submit" value='Filter'/>
        </div>
    </form>
    <script type="text/javascript">
        $( document ).ready(function() {
            $("option").click( function() { 
                    if ( $(this).selected ) {
                        $(this).removeAttr('selected');
                    } else {
                        $(this).attr('selected', 'selected');
                    }
            })
        });
    </script>
{% endblock %}

templates/voters/sample.html
{% extends "voters/base.html" %}

{% block content %}

    <h1>Voters sample</h1>

    <table class="table table-sm">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>Phone</th>
            </tr>
        </thead>
        {% for obj in object_list %}
        <tr>
            <td><a href="{% url 'voters:detail' obj.ncid %}">{{ obj.full_name }}</a></td>
            <td>
                {{ obj.res_street_address }}
            </td>
            <td>
                {{ obj.res_city_desc }}
            </td>
            <td>
                {{ obj.full_phone_number }}
            </td>
        </tr>
        {% endfor %}
    </table>

{% endblock %}